# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0004_addbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTrips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('travel_start', models.DateTimeField(auto_now_add=True)),
                ('travel_end', models.DateTimeField(auto_now_add=True)),
                ('plan', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AddBooks',
        ),
    ]
