# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-27 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0006_addtrips_my_trips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('travel_start', models.DateTimeField(auto_now_add=True)),
                ('travel_end', models.DateTimeField(auto_now_add=True)),
                ('plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Registration',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='addtrips',
            name='my_trips',
        ),
        migrations.DeleteModel(
            name='AddTrips',
        ),
        migrations.AddField(
            model_name='trips',
            name='my_trips',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='first_apps.User'),
        ),
    ]
