# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-27 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0003_auto_20180727_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='my_wishes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='first_apps.User'),
            preserve_default=False,
        ),
    ]
