# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0004_auto_20180725_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
