# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0005_remove_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
