# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0006_auto_20180725_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
    ]
