# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dojos',
            new_name='Dojo',
        ),
    ]
